logging.level:
  org.springframework.jdbc.core: TRACE
spring:
  h2.console.enabled: true
  #  jpa:
  #    hibernate:
  #      ddl-auto: validate
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
