spring:
  profiles:
    active: test
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      default_batch_fetch_size: 1000

  flyway:
    locations: classpath:/db/migration  # 파일 위치
    sql-migration-suffixes: ddl         # 파일 확장자
    baseline-on-migrate: true           # flyway_schema_history 테이블을 자동으로 생성할지 여부
    baseline-version: 0

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE


